### ISSUE TITLE
Wrap `Phoenix.LiveViewTest.render_async/1`?

### ISSUE THREAD

**Issue by RoyalIcing** [germsvel/phoenix_test#103]
I am using the new `assign_async` functionality, and so when visiting a route the data is asynchronously loaded.

`Phoenix.LiveViewTest` provides `render_async/1` to wait for these: https://hexdocs.pm/phoenix_live_view/1.0.0-rc.6/Phoenix.LiveViewTest.html#render_async/2

I tried using `unwrap/2` like so but it did not work:

```elixir
  conn
    |> visit("/path")
    |> unwrap(fn view ->
      Phoenix.LiveViewTest.render_async(view)
    end)
```

The error I received was `** (stop) exited in: GenServer.call(#PID<0.741.0>, {:phoenix, :ping}, :infinity)`

Thanks, it’s a great library!

**Comment by RoyalIcing** [comment]
Actually correction, I have got unwrap to work. That’s great. Any consideration about adding a built-in wrapper, that would perhaps skip if the underlying is a dead view? Perhaps a option to pass like so `visit(path, wait_for_async: true)`?

**Comment by germsvel** [comment]
Hey @RoyalIcing! Good to see you here. 

Yeah, I've thought about adding something like it. 

I  don't think I would make it an option to `visit` because we can also use `render_async/1` with LiveView's `start_async`, and that can be used outside of the original `mount/3`. 

So, I was thinking something like a `wait_for_async/1` function that takes the session and basically does what you're doing in `unwrap/2`. But I haven't figured out a good strategy for exposing functions that are LiveView-only yet. 

I also worry that the name might be a bit too generic and confuse people (since it only works with LiveView's `assign_async` and `start_async`, but I don't think it works with a one-off `Task`). 

If you have ideas, I'd love to hear them!

**Comment by germsvel** [comment]
@RoyalIcing I'm trying to get a gut check here, and I'd love to hear your thoughts. 

I have an experimental branch where I explored the idea of a more generic "waiting" mechanism that would handle async assigns. So, we wouldn't have a `wait_for_async` or anything like that. 

Instead, the `assert_has` helper would take a `timeout` option that would specify how long you want to wait for the results. By default, it would not wait at all -- just like it is today. But if you have a LiveView that renders async, you could pass a timeout and wait: 

```elixir
conn
|> visit("/path")
|> assert_has("#my-data", text: "async data", timeout: 1000)
```

What do you think?

**Comment by RoyalIcing** [comment]
I like it! I think the trade-off is that you'd add the timeout only on the first assert (if you had a chain) but I think in a way that makes sense.

**Comment by germsvel** [comment]
@RoyalIcing PhoenixTest v0.5.0 now has an experimental `timeout` option on assertions that will wait for async operations. Check it out when you can! In the meantime, I'll mark this as closed, since I think that should take care of it.
