### ISSUE TITLE
Add `add_to_active_form(session, name, value)` aka unwrap_form

### ISSUE THREAD

**Issue by ftes** [germsvel/phoenix_test#121]
I want to write as much "vanilla PhoenixTest" as possible.
Even if I'm prevented from filling out some field via PhoenixTest, e.g. due to
- bug
- missing feature (#108, #118, #120)
- Javascript required

Currently, I could call `unwrap/2`. But then I have to "fill out" the rest of the form via plain old LiveView test/controller test means. Potentially making large parts of the test less readable.

A small extension of the the PhoenixTest API could help to
1. keep tests as readable as possible
2. while also taking the pressure off PhoenixTest to handle everything perfectly.

Example
```ex
|> fill_in("User name", with: "Gimli")
# usually set by a Javascript control
|> add_to_active_form("user_tags", "dwarf,outspoken")
|> click_button("Save")
```

**Comment by germsvel** [comment]
@ftes though I understand of wanting to keep in PhoenixTest as much as possible (and agree with the sentiment - I've felt the pain when having to `#unwrap` too much), I'm not sure I want to expose that second level as an API yet. 

Even though having to drop completely to LiveViewTest with `#unwrap` feels a bit painful, I think it's a good escape hatch (since it should _presumably_ let you do anything you'd be doing outside of `phoenix_test`). 

My concern with exposing a lower-level API right now is that I want to keep all internals able to change without us causing breaking changes to users. As soon as we expose that API, we're unable to change how we keep track of forms internally (at least to a certain degree). Maybe once PhoenixTest is in a more stable place, I'd be open to adding another escape hatch at that level.

**Comment by ftes** [comment]
> My concern with exposing a lower-level API right now is that I want to keep all internals able to change without us causing breaking changes to users.

I understand that concern and think it is valid.

Moving away from "unwrap_form" - do you think this would expose any internals:

```ex
|> add_value(input_name, input_value)
```

It is specified at the HTML level (input name/value).
The only internal _implicitly_ exposed is the driver's `active_form`. Because that is where the value would have to be added without widening the API any further.
