### ISSUE TITLE
Can't seem to click_button that has no text

### ISSUE THREAD

**Issue by mxgrn** [germsvel/phoenix_test#152]
Sometimes, a button contains just an icon, in which case I can't seem to be able to 'click' that button.

**Comment by germsvel** [comment]
Thanks for opening this issue @mxgrn. Yeah, this is something I've come across too. I don't have a perfect solution for this because `click_button/2` and `click_link/2` expect the text of the button. 

For now, what I've done is to target the button via CSS selector and leave the text empty: 

```elixir
session
|> click_button("#button-id", "")
```

Not the cleanest solution, but I think that _should_ work. 

In the future, it'd be nice to make allow the text (third argument) be the alt text or something like that. But we're not there yet.

**Comment by mxgrn** [comment]
Bummer that it actually was the first thing I tried out, but something else must have been off, which is why it didn't work on the first attempt. It works now, happily closing! Thanks German!

**Comment by mxgrn** [comment]
Btw, together with @s3cur3 we found an even better solution, `<span class="sr-only">Do something</span>` as the button inner content, next to the icon. Then `click_button("Do something")` works, too!

**Comment by germsvel** [comment]
@mxgrn of course! That's a far better solution. Ideally, that's the kind of thing we can do automatically with `alt` text or some other accessibility default -- i.e. look for the text a screen reader would read out loud.
